defaults:
  - /app@limits: limits
  - /app@system: system
  - /app@prompts: prompts
  - /app@assets: assets
  - /infra@data: data
  - /infra@database: database
  - /infra@rag: rag
  - llm: gemini
  - _self_