defaults:
  - _self_
  - llm: local
  - db: rdb                         # rdb.yaml 파일을 사용하도록 설정
  - prompts/arena@prompts
  - prompts/verdict@prompts        
  - prompts/analyst_agent@prompts  

data:
  raw_path: ${hydra:runtime.cwd}/data/sample