# conf/config.yaml
defaults:
  - _self_

# 데이터 처리 관련 설정
extraction:
  files: [
    "copper_silver.csv", 
    "corn_and_price_or_demand_or_supply_or_inventory.csv", 
    "soy_oil_and_production_or_outputs_or_supplies_or_supply_or_biofuel_or_biodiesel_or_demand_or_price.csv", 
    "soybean_oil_and_production_or_outputs_or_supplies_or_supply_or_biofuel_or_biodiesel_or_demand_or_price.csv", 
    "soybean_and_price_or_demand_or_supply_or_inventory.csv", 
    "gold_future.csv", 
    "fomc_and_fed.csv", 
    "united_states_department_of_agriculture.csv", 
    "soybean_production.csv", 
    "wheat_and_price_or_demand_or_supply_or_inventory.csv", 
    "national_agricultural_statistics_service.csv", 
  ]  # 처리할 CSV 파일명 리스트 (예: ["soybean.csv"])
  # date_start: 2017-01-01 # "2017-01-01"
  # date_end: 2018-12-31   # "2025-12-31"
  window_size: 3   # 윈도우 크기 (일)
  max_articles_per_window: 50
  chunk_size: 50000
  resume: true
  output_dir: "outputs/events/v6_3d"

# LLM 관련 설정
llm:
  temperature: 0
  model: "local_model"